# Generated by Django 3.2.6 on 2021-08-09 08:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=280, null=True)),
                ('military_service_status', models.CharField(blank=True, choices=[('CO', 'Conscript'), ('EE', 'Educational Exemption'), ('E', 'Exempt'), ('D', 'Discharge')], max_length=2, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married')], max_length=1, null=True)),
                ('city_of_residence', models.CharField(blank=True, max_length=80, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.ManyToManyField(to='jobs.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('minimum_work_experience', models.IntegerField(default=0)),
                ('type_of_cooperation', models.CharField(choices=[('full_time', 'full time'), ('part_time', 'part time')], max_length=10)),
                ('minimum_degree', models.CharField(blank=True, choices=[('DI', 'High School Diploma'), ('A', 'Associate Degree'), ('B', 'Bachelors Degree'), ('M', 'Masters Degree'), ('DO', 'Doctoral Degree'), ('P', 'Post Doctoral Degree'), ('O', 'Others')], max_length=2, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('skills_required', models.ManyToManyField(blank=True, to='jobs.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=80)),
                ('institute', models.CharField(max_length=80)),
                ('level', models.CharField(choices=[('DI', 'High School Diploma'), ('A', 'Associate Degree'), ('B', 'Bachelors Degree'), ('M', 'Masters Degree'), ('DO', 'Doctoral Degree'), ('P', 'Post Doctoral Degree'), ('O', 'Others')], max_length=2)),
                ('start_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1450)])),
                ('finish_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1450)])),
                ('is_currently_studying', models.BooleanField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.userprofile')),
            ],
        ),
    ]
