# Generated by Django 3.2.6 on 2021-08-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsOfSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('minimum_work_experience', models.IntegerField(default=0)),
                ('type_of_cooperation', models.CharField(choices=[('full_time', 'full time'), ('part_time', 'part time')], default='full time', max_length=10)),
                ('minimum_degree', models.CharField(choices=[('Diploma', 'دیپلم'), ('Bachelor', 'کارشناسی'), ('Master', 'کارشناسی ارشد'), ('PHD', 'دکترا')], default='Diploma', max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('skills_required', models.ManyToManyField(to='jobs.TagsOfSkill')),
            ],
        ),
    ]
