# Generated by Django 3.2.6 on 2021-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
