# Generated by Django 3.2.6 on 2021-09-06 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0013_joboffer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='users_tagged_job',
            field=models.ManyToManyField(blank=True, related_name='tagged_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
