# Generated by Django 3.2.6 on 2021-09-07 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_joboffer_users_tagged_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalbackground',
            name='finish_year',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1450)], verbose_name='Finish year'),
        ),
    ]
