version: "3"

services:
  website:
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - config/.env.dev
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - CELERY_TASK_ALWAYS_EAGER

  redis:
    image: m.docker-registry.ir/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD
    volumes:
      - redis_dev_data:/redis/data

  db:
    image: m.docker-registry.ir/postgres:latest
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_HOST_AUTH_METHOD

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
