apiVersion: v1
kind: Service
metadata:
  name: jobs-db
  namespace: sc-development
spec:
  selector:
    name: jobs-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: db-port
      protocol: TCP
