# Generated by Django 3.2.6 on 2021-08-21 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_joboffer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalbackground',
            name='field',
            field=models.CharField(max_length=80, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='finish_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1450)], verbose_name='Finish year'),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='institute',
            field=models.CharField(max_length=80, verbose_name='Institue'),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='is_currently_studying',
            field=models.BooleanField(verbose_name='Is currently studying'),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='level',
            field=models.CharField(choices=[('DI', 'High School Diploma'), ('A', 'Associate Degree'), ('B', 'Bachelors Degree'), ('M', 'Masters Degree'), ('DO', 'Doctoral Degree'), ('P', 'Post Doctoral Degree'), ('O', 'Others')], max_length=2, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='start_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1450)], verbose_name='Start year'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city_of_residence',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='City of residence'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married')], max_length=1, null=True, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='military_service_status',
            field=models.CharField(blank=True, choices=[('CO', 'Conscript'), ('EE', 'Educational Exemption'), ('E', 'Exempt'), ('D', 'Discharge')], max_length=2, null=True, verbose_name='Military service status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone number'),
        ),
    ]
