# Generated by Django 3.2.6 on 2021-08-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20210821_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('verification_token', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_emails', to='jobs.userprofile')),
            ],
        ),
    ]
